DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `REF_CODE` varchar(12) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `TITLE` varchar(20) DEFAULT NULL,
  `FIRSTNAME` varchar(50) DEFAULT NULL,
  `LASTNAME` varchar(50) DEFAULT NULL,
  `PHONE` varchar(10) DEFAULT NULL,
  `SALARY` decimal(8,2) NOT NULL,
  `HOUSE_NO` varchar(10) DEFAULT NULL,
  `MOO` int DEFAULT NULL,
  `STREET` varchar(50) DEFAULT NULL,
  `ROAD` varchar(50) DEFAULT NULL,
  `SUB_DISTRICT` varchar(50) DEFAULT NULL,
  `DISTRICT` varchar(50) DEFAULT NULL,
  `PROVINCE` varchar(50) DEFAULT NULL,
  `POSTCODE` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MEMBER_TYPE` enum('PLATINUM','GOLD','SILVER') DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  UNIQUE KEY `REF_CODE_UNIQUE` (`REF_CODE`),
  UNIQUE KEY `PHONE_UNIQUE` (`PHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;